export {Home} from "./Home/Home"
export {Movies} from "./Movies/Movies"
// export {Login} from "./Login/Login"
export {FormLogin} from "./Login/FormLogin"
export {FormRegister} from "./Login/FormRegister"
export {DeleteMovie} from "./Movies/DeleteMovie"
export {ViewMovie} from "./Movies/ViewMovie"
export {EditMovie} from "./Movies/EditMovie"
export {AddMovie} from "./Movies/AddMovie"